// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1GXP5j0hYW-_j5h1CI95bfgpj9hwcTJk',
    appId: '1:320438447867:web:829bb8ce79b82aa9398a5e',
    messagingSenderId: '320438447867',
    projectId: 'firestore-demo-c06bd',
    authDomain: 'firestore-demo-c06bd.firebaseapp.com',
    databaseURL: 'https://firestore-demo-c06bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firestore-demo-c06bd.appspot.com',
    measurementId: 'G-9M1GMHJV30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAck_yROm0xoBqsq-Ke7QquwGc6M04zl5U',
    appId: '1:320438447867:android:c48edbee431d570e398a5e',
    messagingSenderId: '320438447867',
    projectId: 'firestore-demo-c06bd',
    databaseURL: 'https://firestore-demo-c06bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firestore-demo-c06bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeulIrVp2FvPfWOm5gIFM2Ve4BVDvYcsg',
    appId: '1:320438447867:ios:51689b315fcafbca398a5e',
    messagingSenderId: '320438447867',
    projectId: 'firestore-demo-c06bd',
    databaseURL: 'https://firestore-demo-c06bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firestore-demo-c06bd.appspot.com',
    androidClientId: '320438447867-3re5b3b2tsiabo6do7u7jm0vv7daup1o.apps.googleusercontent.com',
    iosClientId: '320438447867-lmi7ijveqjohbj8decql3hiu9gapbmj1.apps.googleusercontent.com',
    iosBundleId: 'com.vedantbhavsar1997.que.que',
  );
}
